### ISSUE TITLE
Cant pull docker image through ipfs 

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-cli#824]
Please include in your bug report:

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Eris CLI Version: 0.12.0

go version go1.6 linux/amd64

ubuntu 14.04 on VM

Pull chain Docker file using ipfs 

eris services import idi QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx
GETing file from IPFS. Hash =>	QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx:/home/vishad/.eris/services/idi.toml
Downloading http://0.0.0.0:8080/ipfs/QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx to /home/vishad/.eris/services/idi.toml
Get http://0.0.0.0:8080/ipfs/QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx: dial tcp 0.0.0.0:8080: getsockopt: connection refused

eris services import idi QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx

**Comment by zramsay** [comment]
Hi @infinius12345 this often happens when ipfs was just started and is usually solved by re-running the command. I see that the file is not loading via the ipfs gateway (gateway.ipfs.io/ipfs/QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx), did you run `eris services export idi` to get the hash?

**Comment by infinius12345** [comment]
infinius@infinius-VirtualBox:~/.eris/apps/idi-service$ eris services export idi
Posting file to IPFS                     file=/home/infinius/.eris/services/idi.toml
Uploading                                file=/home/infinius/.eris/services/idi.toml
                                          url=http://0.0.0.0:8080/ipfs/
                                         hash=QmQstLCGJTEoefPM95yUGtv4Fp8MpNRPGytLQ8ekqrZXFx

**Comment by infinius12345** [comment]
Hi, i was able to get ipfs working but the idi cant find the image
infinius@infinius-VirtualBox:~/.eris/services$ eris services start idi
The Docker image not found locally      image=infinius/idiservice
Would you like the marmots to pull it from the repository? (y/n): y
latest: Pulling from infinius/idiservice
Digest: sha256:0d108b1cbfe7dd6c2051afbc363c08c3f9abb5b9b7c3c52ba8615fa5e0daae26
Status: Image is up to date for infinius/idiservice:latest
Error starting service idi: no such image

**Comment by infinius12345** [comment]
Hi, does anyone know how to make eris reference the image pulled by docker/ipfs ? I am still getting this error

**Comment by zramsay** [comment]
Try `docker pull infinius/idiservice` then rerun `services start`

**Comment by infinius12345** [comment]
docker pull infinius/idiservice
Using default tag: latest
latest: Pulling from infinius/idiservice
Digest: sha256:0d108b1cbfe7dd6c2051afbc363c08c3f9abb5b9b7c3c52ba8615fa5e0daae26
Status: Image is up to date for infinius/idiservice:latest
mishravi@mishravi-VirtualBox:~/.eris/services$ eris services start idi
The Docker image not found locally      image=infinius/idiservice
Would you like the marmots to pull it from the repository? (y/n): y
latest: Pulling from infinius/idiservice
Digest: sha256:0d108b1cbfe7dd6c2051afbc363c08c3f9abb5b9b7c3c52ba8615fa5e0daae26
Status: Image is up to date for infinius/idiservice:latest
Error starting service idi: no such image

**Comment by infinius12345** [comment]
Hi, i had to setup a new VM and did everything again and it worked fine,
I had a question- how can i see the history of my blockchain? or is there a way to see all the blocks?

**Comment by zramsay** [comment]
Ah yes, restarting your `docker-machine` does often fix the issue.

The javascript library for eris-db can be used to inspect history: https://github.com/eris-ltd/eris-db.js

`eris chains logs chainName` will also output logs ... that log output can be set by modifying [this line](https://github.com/eris-ltd/eris-chains/blob/master/config.toml#L12) using the params from `mintconfig` [with these options](https://github.com/eris-ltd/mint-client/blob/7bfac043f9b6df717dac8d6e01042f1f291f3d87/mintconfig/main.go#L38)
